In [1]:
import requests
import urllib3
from strava_secrets_request import getFullHeaderWithAccessToken
urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)



auth_url = "https://www.strava.com/oauth/token"
activites_url = "https://www.strava.com/api/v3/athlete/activities"

header = getFullHeaderWithAccessToken()

request_page_num = 1
all_activities = []

while True:
    param = {'per_page': 50, 'page': request_page_num}
    # initial request, where we request the first page of activities
    my_dataset = requests.get(activites_url, headers=header, params=param).json()

    # check the response to make sure it is not empty. If it is empty, that means there is no more data left. So if you have
    # 1000 activities, on the 6th request, where we request page 6, there would be no more data left, so we will break out of the loop
    if len(my_dataset) == 0:
        print("breaking out of while loop because the response is zero, which means there must be no more activities")
        break

    # if the all_activities list is already populated, that means we want to add additional data to it via extend.
    if all_activities:
        print("all_activities is populated")
        all_activities.extend(my_dataset)

    # if the all_activities is empty, this is the first time adding data so we just set it equal to my_dataset
    else:
        print("all_activities is NOT populated")
        all_activities = my_dataset

    request_page_num += 1

Requesting Token...

all_activities is NOT populated
all_activities is populated
all_activities is populated
breaking out of while loop because the response is zero, which means there must be no more activities

In [2]:
print(len(all_activities))
for count, activity in enumerate(all_activities):
    print(activity["name"])
    print(count)

132
Kleiner Feierabendsprint
0
Fahrt am Nachmittag
1
Radfahrt am Nachmittag
2
Radfahrt am Nachmittag
3
New Bike Day
4
Automatisierung am Nachmittag
5
Radfahrt am Morgen
6
Radfahrt am Nachmittag
7
Entspannte Feierabendrunde
8
Mini OKF
9
Radfahrt am Mittag
10
Tour am 1. Mai
11
Radfahrt am Abend
12
Fahrt nach Tornau
13
Montagsgravel
14
Wanderung am Mittag
15
Wanderung am Morgen
16
Wanderung am Morgen
17
Mini-Feierabendrunde
18
Radfahrt am Nachmittag
19
Radfahrt am Nachmittag
20
Radfahrt am Nachmittag
21
Bitterfeld noch nicht komplett im Arsch
22
Tour de Eierlikör
23
Ostertour
24
OKF
25
Regeneration II / OKF
26
Regeneration
27
Mittagsradfahrt
28
Vollgas für Werni
29
Fahrt am Nachmittag
30
Fahrt am Nachmittag
31
Der Wind ist mein Berg
32
Going Home
33
Brüderliche Seenrunde
34
Seenrunde
35
Mulderadweg entdecken
36
Feierabend im Regen und am Ende geht die Luft aus
37
Feierabend im Regen
38
Neues Cube abholen
39
Fahrt am Nachmittag
40
Fahrt am Nachmittag
41
Fahrt am Nachmittag
42
Lauf am Nachmittag
43
Fahrt am Nachmittag
44
Waldwege im Januar
45
Fahrt am Nachmittag
46
Lauf am Nachmittag
47
Lauf am Abend
48
Lauf am Nachmittag
49
Die 10 in Sicht
50
Lauf am Nachmittag
51
Lauf am Morgen
52
Ischgl
53
Fahrt am Nachmittag
54
Lauf am Nachmittag
55
Durchhalten
56
Mittwochsrunde
57
Wanderung am Morgen
58
Radfahrt am Nachmittag
59
Radfahrt am Nachmittag
60
Radfahrt der Sackgassen
61
Inline-Skating-Einheit am Nachmittag
62
Radfahrt am Nachmittag
63
Lauf am Abend
64
Fahrt am Nachmittag
65
Lauf am Nachmittag
66
Lauf am Nachmittag
67
Mit Rückenwind
68
Inliner-Retter
69
Fahrt am Morgen
70
Durchhalten
71
Radfahrt am Nachmittag
72
Radfahrt am Mittag
73
Lauf am Abend
74
Lauf am Abend
75
Lauf am Abend
76
Ich war auch beim Sputnik
77
Pfingstlauf
78
Lauf
79
Fahrt am Morgen
80
Fahrt am Morgen
81
BTF nach Kanena
82
Fahrt am Morgen
83
Lauf am Abend
84
Lauf am Abend
85
Fahrt am Nachmittag
86
Lauf am Abend
87
Lauf am Abend
88
Radfahrt am Nachmittag
89
Radfahrt am Nachmittag
90
Radfahrt am Mittag
91
Lauf am Mittag
92
Lauf am Nachmittag
93
Lauf am Abend
94
Lauf am Abend
95
Lauf am Nachmittag
96
Lauf am Abend
97
Lauf am Mittag
98
Lauf am Abend
99
Lauf am Mittag
100
Lauf am Mittag
101
Lauf am Abend
102
Lauf am Mittag
103
Lauf am Abend
104
Lauf am Abend
105
Mittagswanderung
106
Firmenlauf
107
Abendlauf
108
Lauf am Mittag
109
Radfahrt am Nachmittag
110
Inline-Skating-Einheit zur Mittagszeit
111
Inline-Skating-Einheit am Morgen
112
Lauf am Abend
113
Lauf am Abend
114
Lauf am Abend
115
Lauf am Abend
116
Inline-Skating-Einheit am Nachmittag
117
Lauf am Abend
118
Lauf am Nachmittag
119
Lauf am Mittag
120
Lauf am Nachmittag
121
Lauf am Mittag
122
Strandlauf
123
Lauf am Mittag
124
Lauf am Abend
125
Lauf am Nachmittag
126
Lauf am Nachmittag
127
Lauf am Morgen
128
Lauf am Nachmittag
129
Lauf am Morgen
130
Lauf am Morgen
131

In [3]:
import pandas as pd
from pandas import json_normalize

activities = json_normalize(all_activities)
activities.columns

Index(['resource_state', 'name', 'distance', 'moving_time', 'elapsed_time',
       'total_elevation_gain', 'type', 'sport_type', 'workout_type', 'id',
       'start_date', 'start_date_local', 'timezone', 'utc_offset',
       'location_city', 'location_state', 'location_country',
       'achievement_count', 'kudos_count', 'comment_count', 'athlete_count',
       'photo_count', 'trainer', 'commute', 'manual', 'private', 'visibility',
       'flagged', 'gear_id', 'start_latlng', 'end_latlng', 'average_speed',
       'max_speed', 'average_watts', 'device_watts', 'kilojoules',
       'has_heartrate', 'heartrate_opt_out', 'display_hide_heartrate_option',
       'elev_high', 'elev_low', 'upload_id', 'upload_id_str', 'external_id',
       'from_accepted_tag', 'pr_count', 'total_photo_count', 'has_kudoed',
       'athlete.id', 'athlete.resource_state', 'map.id',
       'map.summary_polyline', 'map.resource_state'],
      dtype='object')

In [4]:
activities.head(3)

,resource_state,name,distance,moving_time,elapsed_time,total_elevation_gain,type,sport_type,workout_type,id,...,external_id,from_accepted_tag,pr_count,total_photo_count,has_kudoed,athlete.id,athlete.resource_state,map.id,map.summary_polyline,map.resource_state
0,2,Kleiner Feierabendsprint,20457.6,2345,2345,50.3,Ride,Ride,10.0,14552262855,...,53c98ca8-4627-4035-a50e-85eb0b291aac-activity.fit,False,3,0,False,30248736,1,a14552262855,}adzHatdjALCHM`AsEHOJIN@f@`@~@bAjAlBRTPHHG^w@z...,2
1,2,Fahrt am Nachmittag,28318.7,6019,6625,20.6,Ride,Ride,NaN,14530842934,...,stripped_accepted_tag_from_15504993006.tcx,True,0,0,False,30248736,1,a14530842934,i|czHuzdjAtAlAtA~Bj@@pA_D`CmEj@aB~CwEoAlB_A?cA...,2
2,2,Radfahrt am Nachmittag,40525.4,5223,5325,84.2,Ride,Ride,10.0,14529427643,...,1ba87563-f89a-4df4-b1ac-aa5bf65ae362-activity.fit,False,0,0,False,30248736,1,a14529427643,gadzHstdjA`AqE`@a@zBrBnAvBZDdDmGzGuK_ClCSCoAmI...,2

In [5]:
rides = activities.loc[activities['type'] == 'Ride']
runs = activities.loc[activities['type'] == 'Run']

In [6]:
rides.head(3)

,resource_state,name,distance,moving_time,elapsed_time,total_elevation_gain,type,sport_type,workout_type,id,...,external_id,from_accepted_tag,pr_count,total_photo_count,has_kudoed,athlete.id,athlete.resource_state,map.id,map.summary_polyline,map.resource_state
0,2,Kleiner Feierabendsprint,20457.6,2345,2345,50.3,Ride,Ride,10.0,14552262855,...,53c98ca8-4627-4035-a50e-85eb0b291aac-activity.fit,False,3,0,False,30248736,1,a14552262855,}adzHatdjALCHM`AsEHOJIN@f@`@~@bAjAlBRTPHHG^w@z...,2
1,2,Fahrt am Nachmittag,28318.7,6019,6625,20.6,Ride,Ride,NaN,14530842934,...,stripped_accepted_tag_from_15504993006.tcx,True,0,0,False,30248736,1,a14530842934,i|czHuzdjAtAlAtA~Bj@@pA_D`CmEj@aB~CwEoAlB_A?cA...,2
2,2,Radfahrt am Nachmittag,40525.4,5223,5325,84.2,Ride,Ride,10.0,14529427643,...,1ba87563-f89a-4df4-b1ac-aa5bf65ae362-activity.fit,False,0,0,False,30248736,1,a14529427643,gadzHstdjA`AqE`@a@zBrBnAvBZDdDmGzGuK_ClCSCoAmI...,2

In [7]:
sum(rides["distance"])/1000

2001.9564000000005

In [8]:
rides["start_date_local"]

0      2025-05-21T18:09:00Z
1      2025-05-19T17:24:02Z
2      2025-05-19T15:34:42Z
3      2025-05-16T17:48:10Z
4      2025-05-15T17:46:25Z
               ...
86     2024-04-07T13:40:29Z
89     2024-02-25T14:17:31Z
90     2024-02-18T13:38:04Z
91     2024-01-28T12:49:31Z
110    2023-06-21T14:34:30Z
Name: start_date_local, Length: 63, dtype: object

In [9]:
from datetime import datetime
now = datetime.now()
current_month = now.strftime("%Y-%m")
current_month_rides = rides[rides['start_date_local'].str.contains(current_month, na=False)]
#current_month_rides['start_date_local'] = pd.to_datetime(rides['start_date_local'])
#current_month_rides.loc[current_month_rides['start_date_local'] ]
current_month_rides
sum(current_month_rides["distance"])/1000

421.4076000000001

In [10]:
print(current_month_rides["average_speed"].mean() * 3.6)
print(current_month_rides["distance"].mean()/1000)

23.477999999999998
35.1173

In [11]:
max(rides['average_speed']) * 3.6

31.4064