In [47]:
import requests
import urllib3
from strava_secrets_request import getFullHeaderWithAccessToken
urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)



auth_url = "https://www.strava.com/oauth/token"
activites_url = "https://www.strava.com/api/v3/athlete/activities"

header = getFullHeaderWithAccessToken()

request_page_num = 1
all_activities = []

while True:
    param = {'per_page': 50, 'page': request_page_num}
    # initial request, where we request the first page of activities
    my_dataset = requests.get(activites_url, headers=header, params=param).json()

    # check the response to make sure it is not empty. If it is empty, that means there is no more data left. So if you have
    # 1000 activities, on the 6th request, where we request page 6, there would be no more data left, so we will break out of the loop
    if len(my_dataset) == 0:
        print("breaking out of while loop because the response is zero, which means there must be no more activities")
        break

    # if the all_activities list is already populated, that means we want to add additional data to it via extend.
    if all_activities:
        print("all_activities is populated")
        all_activities.extend(my_dataset)

    # if the all_activities is empty, this is the first time adding data so we just set it equal to my_dataset
    else:
        print("all_activities is NOT populated")
        all_activities = my_dataset

    request_page_num += 1

Requesting Token...

Access Token = f06041e206b261dc7ea2ad067b3de9f6557e6729

all_activities is NOT populated
all_activities is populated
all_activities is populated
breaking out of while loop because the response is zero, which means there must be no more activities

In [48]:
print(len(all_activities))
for count, activity in enumerate(all_activities):
    print(activity["name"])
    print(count)

131
Fahrt am Nachmittag
0
Radfahrt am Nachmittag
1
Radfahrt am Nachmittag
2
New Bike Day
3
Automatisierung am Nachmittag
4
Radfahrt am Morgen
5
Radfahrt am Nachmittag
6
Entspannte Feierabendrunde
7
Mini OKF
8
Radfahrt am Mittag
9
Tour am 1. Mai
10
Radfahrt am Abend
11
Fahrt nach Tornau
12
Montagsgravel
13
Wanderung am Mittag
14
Wanderung am Morgen
15
Wanderung am Morgen
16
Mini-Feierabendrunde
17
Radfahrt am Nachmittag
18
Radfahrt am Nachmittag
19
Radfahrt am Nachmittag
20
Bitterfeld noch nicht komplett im Arsch
21
Tour de Eierlikör
22
Ostertour
23
OKF
24
Regeneration II / OKF
25
Regeneration
26
Mittagsradfahrt
27
Vollgas für Werni
28
Fahrt am Nachmittag
29
Fahrt am Nachmittag
30
Der Wind ist mein Berg
31
Going Home
32
Brüderliche Seenrunde
33
Seenrunde
34
Mulderadweg entdecken
35
Feierabend im Regen und am Ende geht die Luft aus
36
Feierabend im Regen
37
Neues Cube abholen
38
Fahrt am Nachmittag
39
Fahrt am Nachmittag
40
Fahrt am Nachmittag
41
Lauf am Nachmittag
42
Fahrt am Nachmittag
43
Waldwege im Januar
44
Fahrt am Nachmittag
45
Lauf am Nachmittag
46
Lauf am Abend
47
Lauf am Nachmittag
48
Die 10 in Sicht
49
Lauf am Nachmittag
50
Lauf am Morgen
51
Ischgl
52
Fahrt am Nachmittag
53
Lauf am Nachmittag
54
Durchhalten
55
Mittwochsrunde
56
Wanderung am Morgen
57
Radfahrt am Nachmittag
58
Radfahrt am Nachmittag
59
Radfahrt der Sackgassen
60
Inline-Skating-Einheit am Nachmittag
61
Radfahrt am Nachmittag
62
Lauf am Abend
63
Fahrt am Nachmittag
64
Lauf am Nachmittag
65
Lauf am Nachmittag
66
Mit Rückenwind
67
Inliner-Retter
68
Fahrt am Morgen
69
Durchhalten
70
Radfahrt am Nachmittag
71
Radfahrt am Mittag
72
Lauf am Abend
73
Lauf am Abend
74
Lauf am Abend
75
Ich war auch beim Sputnik
76
Pfingstlauf
77
Lauf
78
Fahrt am Morgen
79
Fahrt am Morgen
80
BTF nach Kanena
81
Fahrt am Morgen
82
Lauf am Abend
83
Lauf am Abend
84
Fahrt am Nachmittag
85
Lauf am Abend
86
Lauf am Abend
87
Radfahrt am Nachmittag
88
Radfahrt am Nachmittag
89
Radfahrt am Mittag
90
Lauf am Mittag
91
Lauf am Nachmittag
92
Lauf am Abend
93
Lauf am Abend
94
Lauf am Nachmittag
95
Lauf am Abend
96
Lauf am Mittag
97
Lauf am Abend
98
Lauf am Mittag
99
Lauf am Mittag
100
Lauf am Abend
101
Lauf am Mittag
102
Lauf am Abend
103
Lauf am Abend
104
Mittagswanderung
105
Firmenlauf
106
Abendlauf
107
Lauf am Mittag
108
Radfahrt am Nachmittag
109
Inline-Skating-Einheit zur Mittagszeit
110
Inline-Skating-Einheit am Morgen
111
Lauf am Abend
112
Lauf am Abend
113
Lauf am Abend
114
Lauf am Abend
115
Inline-Skating-Einheit am Nachmittag
116
Lauf am Abend
117
Lauf am Nachmittag
118
Lauf am Mittag
119
Lauf am Nachmittag
120
Lauf am Mittag
121
Strandlauf
122
Lauf am Mittag
123
Lauf am Abend
124
Lauf am Nachmittag
125
Lauf am Nachmittag
126
Lauf am Morgen
127
Lauf am Nachmittag
128
Lauf am Morgen
129
Lauf am Morgen
130

In [49]:
import pandas as pd
from pandas import json_normalize

activities = json_normalize(all_activities)
activities.columns

Index(['resource_state', 'name', 'distance', 'moving_time', 'elapsed_time',
       'total_elevation_gain', 'type', 'sport_type', 'workout_type', 'id',
       'start_date', 'start_date_local', 'timezone', 'utc_offset',
       'location_city', 'location_state', 'location_country',
       'achievement_count', 'kudos_count', 'comment_count', 'athlete_count',
       'photo_count', 'trainer', 'commute', 'manual', 'private', 'visibility',
       'flagged', 'gear_id', 'start_latlng', 'end_latlng', 'average_speed',
       'max_speed', 'average_watts', 'device_watts', 'kilojoules',
       'has_heartrate', 'heartrate_opt_out', 'display_hide_heartrate_option',
       'elev_high', 'elev_low', 'upload_id', 'upload_id_str', 'external_id',
       'from_accepted_tag', 'pr_count', 'total_photo_count', 'has_kudoed',
       'athlete.id', 'athlete.resource_state', 'map.id',
       'map.summary_polyline', 'map.resource_state'],
      dtype='object')

In [50]:
activities.head(3)

,resource_state,name,distance,moving_time,elapsed_time,total_elevation_gain,type,sport_type,workout_type,id,...,external_id,from_accepted_tag,pr_count,total_photo_count,has_kudoed,athlete.id,athlete.resource_state,map.id,map.summary_polyline,map.resource_state
0,2,Fahrt am Nachmittag,28318.7,6019,6625,20.6,Ride,Ride,NaN,14530842934,...,stripped_accepted_tag_from_15504993006.tcx,True,0,0,False,30248736,1,a14530842934,i|czHuzdjAtAlAtA~Bj@@pA_D`CmEj@aB~CwEoAlB_A?cA...,2
1,2,Radfahrt am Nachmittag,40525.4,5223,5325,84.2,Ride,Ride,10.0,14529427643,...,1ba87563-f89a-4df4-b1ac-aa5bf65ae362-activity.fit,False,0,0,False,30248736,1,a14529427643,gadzHstdjA`AqE`@a@zBrBnAvBZDdDmGzGuK_ClCSCoAmI...,2
2,2,Radfahrt am Nachmittag,34325.3,5324,5530,79.8,Ride,Ride,10.0,14500397085,...,7cb354bb-b614-49d3-be09-81f5a80bd072-activity.fit,False,2,0,False,30248736,1,a14500397085,y}czHy{djApAjAxBdDL@vBmEjI}MGGwBrCO@mAgI]g@_J`...,2

In [51]:
rides = activities.loc[activities['type'] == 'Ride']
runs = activities.loc[activities['type'] == 'Run']

In [52]:
rides.head(3)

,resource_state,name,distance,moving_time,elapsed_time,total_elevation_gain,type,sport_type,workout_type,id,...,external_id,from_accepted_tag,pr_count,total_photo_count,has_kudoed,athlete.id,athlete.resource_state,map.id,map.summary_polyline,map.resource_state
0,2,Fahrt am Nachmittag,28318.7,6019,6625,20.6,Ride,Ride,NaN,14530842934,...,stripped_accepted_tag_from_15504993006.tcx,True,0,0,False,30248736,1,a14530842934,i|czHuzdjAtAlAtA~Bj@@pA_D`CmEj@aB~CwEoAlB_A?cA...,2
1,2,Radfahrt am Nachmittag,40525.4,5223,5325,84.2,Ride,Ride,10.0,14529427643,...,1ba87563-f89a-4df4-b1ac-aa5bf65ae362-activity.fit,False,0,0,False,30248736,1,a14529427643,gadzHstdjA`AqE`@a@zBrBnAvBZDdDmGzGuK_ClCSCoAmI...,2
2,2,Radfahrt am Nachmittag,34325.3,5324,5530,79.8,Ride,Ride,10.0,14500397085,...,7cb354bb-b614-49d3-be09-81f5a80bd072-activity.fit,False,2,0,False,30248736,1,a14500397085,y}czHy{djApAjAxBdDL@vBmEjI}MGGwBrCO@mAgI]g@_J`...,2

In [53]:
sum(rides["distance"])/1000

1981.4988000000005

In [55]:
rides["start_date_local"]

0      2025-05-19T17:24:02Z
1      2025-05-19T15:34:42Z
2      2025-05-16T17:48:10Z
3      2025-05-15T17:46:25Z
4      2025-05-11T16:01:58Z
               ...
85     2024-04-07T13:40:29Z
88     2024-02-25T14:17:31Z
89     2024-02-18T13:38:04Z
90     2024-01-28T12:49:31Z
109    2023-06-21T14:34:30Z
Name: start_date_local, Length: 62, dtype: object

In [57]:
from datetime import datetime
now = datetime.now()
current_month = now.strftime("%Y-%m")
current_month_rides = rides[rides['start_date_local'].str.contains(current_month, na=False)]
#current_month_rides['start_date_local'] = pd.to_datetime(rides['start_date_local'])
#current_month_rides.loc[current_month_rides['start_date_local'] ]
current_month_rides
sum(current_month_rides["distance"])/1000

400.95000000000005

In [60]:
max(rides['average_speed']) * 3.6

29.1924